workflows:
  android-workflow:
    name: Android AAB & APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Expo Prebuild
        script: npx expo prebuild --platform android --clean
      - name: Fix Kotlin Version and Build
        script: |
          # 1. توليد المفتاح
          keytool -genkey -v -keystore shego.keystore -alias shego-key -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -keypass 123456 -dname "CN=Shego, OU=Dev, O=Shego, L=City, S=State, C=US"
          
          # 2. إعداد ملف التوقيع
          echo "RELEASE_STORE_FILE=../shego.keystore" >> android/gradle.properties
          echo "RELEASE_STORE_PASSWORD=123456" >> android/gradle.properties
          echo "RELEASE_KEY_ALIAS=shego-key" >> android/gradle.properties
          echo "RELEASE_KEY_PASSWORD=123456" >> android/gradle.properties
          
          # 3. حل جذري لمشكلة Kotlin: البحث في كافة ملفات gradle وتعديل النسخة
          find android -name "build.gradle" -exec sed -i '' 's/kotlinVersion = .*/kotlinVersion = "1.9.25"/' {} + || find android -name "build.gradle" -exec sed -i 's/kotlinVersion = .*/kotlinVersion = "1.9.25"/' {} +
          find android -name "build.gradle" -exec sed -i '' 's/kotlin_version = .*/kotlin_version = "1.9.25"/' {} + || find android -name "build.gradle" -exec sed -i 's/kotlin_version = .*/kotlin_version = "1.9.25"/' {} +

          # 4. بناء النسخ
          cd android && ./gradlew clean assembleRelease bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/apk/release/*.apk
      - shego.keystore