workflows:
  android-workflow:
    name: Android AAB & APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo Prebuild
        script: npx expo prebuild --platform android
      - name: Generate Keystore and Build
        script: |
          # توليد المفتاح تلقائياً
          keytool -genkey -v -keystore shego.keystore -alias shego-key -keyalg RSA -keysize 2048 -validity 10000 -storepass 123456 -keypass 123456 -dname "CN=Shego, OU=Dev, O=Shego, L=City, S=State, C=US"
          
          # إعداد ملف التوقيع لـ Gradle
          echo "RELEASE_STORE_FILE=../shego.keystore" >> android/gradle.properties
          echo "RELEASE_STORE_PASSWORD=123456" >> android/gradle.properties
          echo "RELEASE_KEY_ALIAS=shego-key" >> android/gradle.properties
          echo "RELEASE_KEY_PASSWORD=123456" >> android/gradle.properties
          
          # بناء النسختين معاً (AAB و APK)
          cd android && ./gradlew assembleRelease bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/apk/release/*.apk
      - shego.keystore